In [1]:
# Mestrado em Engenharia de Computação e Sistemas - Universidade Estadual do Maranhão
# Aluno: Arthur Moura Barbosa

In [2]:
# imports
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import explained_variance_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn import metrics
from sklearn.model_selection import cross_val_predict
from sklearn import model_selection
from scipy.stats import ttest_ind
#
from sklearn.linear_model import LogisticRegression
#
from sklearn.naive_bayes import GaussianNB


In [3]:
# Base 1 - Career Longevity for NBA Rookies (preve a chance de um atleta ter uma carreira com mais de 5 anos e menos de 5 anos)

df1 = pd.read_csv('nba_logreg.csv').dropna() # data frame Career Longevity for NBA Rookies

x_1 = df1[['GP', 'MIN', 'PTS','FGM']]

y_1 = df1['TARGET_5Yrs']

x_1.describe()

GP          MIN          PTS          FGM
count  1329.000000  1329.000000  1329.000000  1329.000000
mean     60.402558    17.647931     6.820166     2.634763
std      17.481092     8.327441     4.365671     1.686850
min      11.000000     3.100000     0.700000     0.300000
25%      47.000000    10.800000     3.700000     1.400000
50%      63.000000    16.100000     5.600000     2.100000
75%      77.000000    22.900000     8.800000     3.400000
max      82.000000    40.900000    28.200000    10.200000

In [4]:
# Base 2 - Breast Cancer (detecção de cancer)

df2 = pd.read_csv('dataR2.csv').dropna()# data frame Breast Cancer

x_2 = df2[['Age','Glucose','Insulin','Adiponectin','Resistin']]

y_2 = df2['Classification']

x_2.describe()

Age     Glucose     Insulin  Adiponectin    Resistin
count  116.000000  116.000000  116.000000   116.000000  116.000000
mean    57.301724   97.793103   10.012086    10.180874   14.725966
std     16.112766   22.525162   10.067768     6.843341   12.390646
min     24.000000   60.000000    2.432000     1.656020    3.210000
25%     45.000000   85.750000    4.359250     5.474282    6.881763
50%     56.000000   92.000000    5.924500     8.352692   10.827740
75%     71.000000  102.000000   11.189250    11.815970   17.755207
max     89.000000  201.000000   58.460000    38.040000   82.100000

In [6]:
# Base 3 - Titanic Surviver (Predição da chance de sobrevivência no Titanic)

df3 = pd.read_csv('train.csv').dropna() # data frame Titanic Surviver

x_3 = df3[['Pclass', 'Sex', 'Age']]

x_3['Sex'].replace(to_replace=['female'], value=0, inplace=True)
x_3['Sex'].replace(to_replace=['male'], value=1, inplace=True)

y_3 = df3['Survived']

x_3.describe()

Pclass         Sex         Age
count  183.000000  183.000000  183.000000
mean     1.191257    0.519126   35.674426
std      0.515187    0.501005   15.643866
min      1.000000    0.000000    0.920000
25%      1.000000    0.000000   24.000000
50%      1.000000    1.000000   36.000000
75%      1.000000    1.000000   47.500000
max      3.000000    1.000000   80.000000

In [7]:
# Regressão Logística

reg = LogisticRegression()

#
modelo_reg_1 = reg.fit(x_1,y_1)
modelo_reg_2 = reg.fit(x_2,y_2)
modelo_reg_3 = reg.fit(x_3,y_3)

In [8]:
# Naive Bayes

gnb = GaussianNB()

#
modelo_gnb_1 = gnb.fit(x_1,y_1)
modelo_gnb_2 = gnb.fit(x_2,y_2)
modelo_gnb_3 = gnb.fit(x_3,y_3)

In [9]:
# Validação

def validacao(X,y, modelo):
    X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.4,random_state=0)


    # Train the model using the training sets
    modelo.fit(X_train,y_train)

    #Predict Output
    y_pred = modelo.predict(X_test)

    #matriz de confusão e metricas
    cnf_matrix = confusion_matrix(y_test, y_pred)

    specificity = cnf_matrix[1,1]/(cnf_matrix[1,0]+cnf_matrix[1,1])

    print("\nMétodo validação 60/40 resutados:")
    print("\nMatriz de confusão:\n",cnf_matrix,'\n')
    print("Accuracy:",accuracy_score(y_test, y_pred))
    print("Precision:",precision_score(y_test, y_pred))
    print('Specificity :', specificity)
    print("Recall:",metrics.recall_score(y_test, y_pred))
    print("F1_score:",metrics.f1_score(y_test, y_pred))

In [10]:
# Validação Base 1

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
print()
validacao(x_1, y_1, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
validacao(x_1, y_1, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------


Método validação 60/40 resutados:

Matriz de confusão:
 [[ 92 116]
 [ 56 268]] 

Accuracy: 0.6766917293233082
Precision: 0.6979166666666666
Specificity : 0.8271604938271605
Recall: 0.8271604938271605
F1_score: 0.7570621468926554

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de confusão:
 [[156  52]
 [124 200]] 

Accuracy: 0.6691729323308271
Precision: 0.7936507936507936
Specificity : 0.6172839506172839
Recall: 0.6172839506172839
F1_score: 0.6944444444444444


In [11]:
# Validação Base 2

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
print()
validacao(x_2, y_2, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
validacao(x_2, y_2, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------


Método validação 60/40 resutados:

Matriz de confusão:
 [[12  8]
 [11 16]] 

Accuracy: 0.5957446808510638
Precision: 0.6666666666666666
Specificity : 0.5925925925925926
Recall: 0.5925925925925926
F1_score: 0.627450980392157

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de confusão:
 [[15  5]
 [17 10]] 

Accuracy: 0.5319148936170213
Precision: 0.6666666666666666
Specificity : 0.37037037037037035
Recall: 0.37037037037037035
F1_score: 0.47619047619047616


In [12]:
# Validação Base 3

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
validacao(x_3, y_3, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
validacao(x_3, y_3, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de confusão:
 [[12  9]
 [ 6 47]] 

Accuracy: 0.7972972972972973
Precision: 0.8392857142857143
Specificity : 0.8867924528301887
Recall: 0.8867924528301887
F1_score: 0.8623853211009174

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de confusão:
 [[14  7]
 [ 7 46]] 

Accuracy: 0.8108108108108109
Precision: 0.8679245283018868
Specificity : 0.8679245283018868
Recall: 0.8679245283018868
F1_score: 0.8679245283018869


In [13]:
def k_fold(X, y, modelo, k=5): 
    y_pred = cross_val_predict(modelo,X,y, cv = k)
    conf_matrix = confusion_matrix(y, y_pred)
    specificity = conf_matrix[1,1]/(conf_matrix[1,0]+conf_matrix[1,1])

    print("\nMétodo k-fold (k=5) resutados:")
    print("\nMatriz de confusão :\n",conf_matrix,'\n')
    print("Accuracy:",metrics.accuracy_score(y, y_pred))
    print("Precision:",metrics.precision_score(y, y_pred))
    print('Specificity :', specificity)
    print("Recall:",metrics.recall_score(y, y_pred))
    print("F1_score:",metrics.f1_score(y, y_pred))

In [14]:
# K-fold (k=5) - Base 1

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
k_fold(x_1, y_1, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
k_fold(x_1, y_1, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão :
 [[261 242]
 [156 670]] 

Accuracy: 0.7005267118133935
Precision: 0.7346491228070176
Specificity : 0.8111380145278451
Recall: 0.8111380145278451
F1_score: 0.7710011507479863

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão :
 [[384 119]
 [336 490]] 

Accuracy: 0.6576373212942062
Precision: 0.8045977011494253
Specificity : 0.5932203389830508
Recall: 0.5932203389830508
F1_score: 0.6829268292682927


In [105]:
# K-fold (k=5) - Base 2

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
k_fold(x_2, y_2, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
k_fold(x_2, y_2, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão :
 [[32 20]
 [21 43]] 

Accuracy: 0.646551724137931
Precision: 0.6825396825396826
Specificity : 0.671875
Recall: 0.671875
F1_score: 0.6771653543307087

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão :
 [[37 15]
 [33 31]] 

Accuracy: 0.5862068965517241
Precision: 0.6739130434782609
Specificity : 0.484375
Recall: 0.484375
F1_score: 0.5636363636363637


In [15]:
# K-fold (k=5) - Base 3

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
k_fold(x_3, y_3, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
k_fold(x_3, y_3, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão :
 [[ 38  22]
 [ 17 106]] 

Accuracy: 0.7868852459016393
Precision: 0.828125
Specificity : 0.8617886178861789
Recall: 0.8617886178861789
F1_score: 0.8446215139442231

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão :
 [[50 10]
 [33 90]] 

Accuracy: 0.7650273224043715
Precision: 0.9
Specificity : 0.7317073170731707
Recall: 0.7317073170731707
F1_score: 0.8071748878923767


In [17]:
def leave_one_out(X, y, modelo):
    loocv = model_selection.LeaveOneOut()
    y_pred_loo = cross_val_predict(modelo,X, y, cv=loocv)
    conf_matrix = confusion_matrix(y, y_pred_loo)

    specificity = conf_matrix[1,1]/(conf_matrix[1,0]+conf_matrix[1,1])

    print("\nMétodo LeaveOneOut resutados:")
    print("\nMatriz de confusão :\n",conf_matrix,'\n')

    print("Accuracy:",metrics.accuracy_score(y, y_pred_loo))
    print("Precision:",metrics.precision_score(y, y_pred_loo))
    print('Specificity :', specificity)
    print("Recall:",metrics.recall_score(y, y_pred_loo))
    print("F1_score:",metrics.f1_score(y, y_pred_loo))

In [18]:
# Leave one out - Base 1

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
leave_one_out(x_1, y_1, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
leave_one_out(x_1, y_1, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------

Método LeaveOneOut resutados:

Matriz de confusão :
 [[259 244]
 [153 673]] 

Accuracy: 0.7012791572610986
Precision: 0.7339149400218102
Specificity : 0.8147699757869249
Recall: 0.8147699757869249
F1_score: 0.772231784279977

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método LeaveOneOut resutados:

Matriz de confusão :
 [[386 117]
 [338 488]] 

Accuracy: 0.6576373212942062
Precision: 0.8066115702479338
Specificity : 0.5907990314769975
Recall: 0.5907990314769975
F1_score: 0.6820405310971348


In [19]:
# Leave one out - Base 2

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
leave_one_out(x_2, y_2, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
leave_one_out(x_2, y_2, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------

Método LeaveOneOut resutados:

Matriz de confusão :
 [[37 15]
 [22 42]] 

Accuracy: 0.6810344827586207
Precision: 0.7368421052631579
Specificity : 0.65625
Recall: 0.65625
F1_score: 0.6942148760330578

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método LeaveOneOut resutados:

Matriz de confusão :
 [[44  8]
 [34 30]] 

Accuracy: 0.6379310344827587
Precision: 0.7894736842105263
Specificity : 0.46875
Recall: 0.46875
F1_score: 0.5882352941176471


In [92]:
# Leave one out - Base 3

print("---------------------------------------------------------------------")
print("Regressão Logística")
print("---------------------------------------------------------------------")
leave_one_out(x_3, y_3, LogisticRegression())
print()
print("---------------------------------------------------------------------")
print("Naive Bayes")
print("---------------------------------------------------------------------")
leave_one_out(x_3, y_3, GaussianNB())

---------------------------------------------------------------------
Regressão Logística
---------------------------------------------------------------------

Método LeaveOneOut resutados:

Matriz de confusão :
 [[ 39  21]
 [ 22 101]] 

Accuracy: 0.7650273224043715
Precision: 0.8278688524590164
Specificity : 0.8211382113821138
Recall: 0.8211382113821138
F1_score: 0.8244897959183674

---------------------------------------------------------------------
Naive Bayes
---------------------------------------------------------------------

Método LeaveOneOut resutados:

Matriz de confusão :
 [[48 12]
 [37 86]] 

Accuracy: 0.73224043715847
Precision: 0.8775510204081632
Specificity : 0.6991869918699187
Recall: 0.6991869918699187
F1_score: 0.7782805429864255


In [73]:
def t_test_validation(X,y, modelo, initial=1, final=11):
    t_test_validation_vector = []
    for x in range(initial,final):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=x)
        modelo.fit(X_train, y_train)
        predito = modelo.predict(X_test)
        t_test_validation_vector.append(accuracy_score(y_test, predito))
        
    return t_test_validation_vector

In [75]:
# T Test - Base 1

t_test_validation_reg = t_test_validation(x_1,y_1, reg)

t_test_validation_gnb = t_test_validation(x_1,y_1, gnb)

ttest_ind(t_test_validation_reg, t_test_validation_gnb)


Ttest_indResult(statistic=7.566199631720906, pvalue=5.371191519023701e-07)

In [56]:
# T Test - Base 2

t_test_validation_reg = t_test_validation(x_2,y_2, reg)

t_test_validation_gnb = t_test_validation(x_2,y_2, gnb)

ttest_ind(t_test_validation_reg, t_test_validation_gnb)


Ttest_indResult(statistic=2.428922714258207, pvalue=0.025843157182938576)

In [55]:
# T Test - Base 3

t_test_validation_reg = t_test_validation(x_3,y_3, reg)

t_test_validation_gnb = t_test_validation(x_3,y_3, gnb)

ttest_ind(t_test_validation_reg, t_test_validation_gnb)


Ttest_indResult(statistic=0.19507682662871964, pvalue=0.8475178408519533)