In [1]:
# Mestrado em Engenharia de Computação e Sistemas - Universidade Estadual do Maranhão
# Aluno: Arthur Moura Barbosa

In [18]:
# imports
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import explained_variance_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn import metrics
from sklearn.model_selection import cross_val_predict
from sklearn import model_selection
from scipy.stats import ttest_ind
from statsmodels.stats.multicomp import MultiComparison
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy import stats
#
from sklearn.linear_model import LogisticRegression
#
from sklearn.naive_bayes import GaussianNB
#
from sklearn.neural_network import MLPClassifier
#
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF


In [4]:
# Base 1 - Career Longevity for NBA Rookies (preve a chance de um atleta ter uma carreira com mais de 5 anos e menos de 5 anos)

df1 = pd.read_csv('nba_logreg.csv').dropna() # data frame Career Longevity for NBA Rookies

x_1 = df1[['GP', 'MIN', 'PTS','FGM']]

y_1 = df1['TARGET_5Yrs']

x_1.describe()

GP          MIN          PTS          FGM
count  1329.000000  1329.000000  1329.000000  1329.000000
mean     60.402558    17.647931     6.820166     2.634763
std      17.481092     8.327441     4.365671     1.686850
min      11.000000     3.100000     0.700000     0.300000
25%      47.000000    10.800000     3.700000     1.400000
50%      63.000000    16.100000     5.600000     2.100000
75%      77.000000    22.900000     8.800000     3.400000
max      82.000000    40.900000    28.200000    10.200000

In [5]:
# Base 2 - Breast Cancer (detecção de cancer)

df2 = pd.read_csv('dataR2.csv').dropna()# data frame Breast Cancer

x_2 = df2[['Age','Glucose','Insulin','Adiponectin','Resistin']]

y_2 = df2['Classification']

x_2.describe()

Age     Glucose     Insulin  Adiponectin    Resistin
count  116.000000  116.000000  116.000000   116.000000  116.000000
mean    57.301724   97.793103   10.012086    10.180874   14.725966
std     16.112766   22.525162   10.067768     6.843341   12.390646
min     24.000000   60.000000    2.432000     1.656020    3.210000
25%     45.000000   85.750000    4.359250     5.474282    6.881763
50%     56.000000   92.000000    5.924500     8.352692   10.827740
75%     71.000000  102.000000   11.189250    11.815970   17.755207
max     89.000000  201.000000   58.460000    38.040000   82.100000

In [6]:
# Base 3 - Titanic Surviver (Predição da chance de sobrevivência no Titanic)

df3 = pd.read_csv('train.csv').dropna() # data frame Titanic Surviver

x_3 = df3[['Pclass', 'Sex', 'Age']]

x_3['Sex'].replace(to_replace=['female'], value=0, inplace=True)
x_3['Sex'].replace(to_replace=['male'], value=1, inplace=True)

y_3 = df3['Survived']

x_3.describe()

C:\Users\Arthur\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


Pclass         Sex         Age
count  183.000000  183.000000  183.000000
mean     1.191257    0.519126   35.674426
std      0.515187    0.501005   15.643866
min      1.000000    0.000000    0.920000
25%      1.000000    0.000000   24.000000
50%      1.000000    1.000000   36.000000
75%      1.000000    1.000000   47.500000
max      3.000000    1.000000   80.000000

In [7]:
# Regressão Logística

reg = LogisticRegression()

#
modelo_reg_1 = reg.fit(x_1,y_1)
modelo_reg_2 = reg.fit(x_2,y_2)
modelo_reg_3 = reg.fit(x_3,y_3)

In [8]:
# Naive Bayes

gnb = GaussianNB()

#
modelo_gnb_1 = gnb.fit(x_1,y_1)
modelo_gnb_2 = gnb.fit(x_2,y_2)
modelo_gnb_3 = gnb.fit(x_3,y_3)

In [9]:
# Rede MLP ‘adam’ Otimizador estocástico baseado em gradiente proposto por Kingma, Diederik e Jimmy Ba

mlp = MLPClassifier(max_iter = 10000)

#
modelo_mlp_1 = mlp.fit(x_1,y_1)
modelo_mlp_2 = mlp.fit(x_2,y_2)
modelo_mlp_3 = mlp.fit(x_3,y_3)

In [10]:
# Rede MLP ‘lbfgs’ Otimizador na família de métodos quase-Newton

mlp_lbfgs = MLPClassifier(solver='lbfgs', max_iter = 10000)

#
modelo_mlp_lbfgs_1 = mlp_lbfgs.fit(x_1,y_1)
modelo_mlp_lbfgs_2 = mlp_lbfgs.fit(x_2,y_2)
modelo_mlp_lbfgs_3 = mlp_lbfgs.fit(x_3,y_3)

In [11]:
# Rede Radial Basis Function (RBF)

kernel = 1.0 * RBF(1.0)

rbf = GaussianProcessClassifier(kernel=kernel,random_state=0)

#
modelo_rbf_1 = rbf.fit(x_1,y_1)
modelo_rbf_2 = rbf.fit(x_2,y_2)
modelo_rbf_3 = rbf.fit(x_3,y_3)

In [12]:
# Rede Radial Basis Function (RBF) Gaussian Process

rbf_gpc = GaussianProcessClassifier()

#
modelo_rbf_gpc_1 = rbf_gpc.fit(x_1,y_1)
modelo_rbf_gpc_2 = rbf_gpc.fit(x_2,y_2)
modelo_rbf_gpc_3 = rbf_gpc.fit(x_3,y_3)

In [13]:
def lreg_nbayes_mlp_rbf_testes(x,y,base,funcao):
    print("---------------------------------------------------------------------")
    print("1) Regressão Logística ("+base+")")
    print("---------------------------------------------------------------------")
    print()
    funcao(x, y, reg)
    print()
    print("---------------------------------------------------------------------")
    print("2) Naive Bayes ("+base+")")
    print("---------------------------------------------------------------------")
    funcao(x, y, gnb)
    print()
    print("---------------------------------------------------------------------")
    print("3) MPL 'adam' ("+base+")")
    print("---------------------------------------------------------------------")
    funcao(x, y, mlp)
    print()
    print("---------------------------------------------------------------------")
    print("4) MPL 'lbfgs' ("+base+")")
    print("---------------------------------------------------------------------")
    funcao(x, y, mlp_lbfgs)
    print()
    print("---------------------------------------------------------------------")
    print("5) RBF ("+base+")")
    print("---------------------------------------------------------------------")
    funcao(x, y, rbf)
    print()
    print("---------------------------------------------------------------------")
    print("6) RBF Gaussian Process ("+base+")")
    print("---------------------------------------------------------------------")
    funcao(x, y, rbf_gpc)

In [14]:
# Validação

def validacao(X,y, modelo):
    X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.4,random_state=0)


    # Train the model using the training sets
    modelo.fit(X_train,y_train)

    #Predict Output
    y_pred = modelo.predict(X_test)

    #matriz de confusão e metricas
    cnf_matrix = confusion_matrix(y_test, y_pred)

    specificity = cnf_matrix[1,1]/(cnf_matrix[1,0]+cnf_matrix[1,1])

    print("\nMétodo validação 60/40 resutados:")
    print("\nMatriz de confusão:\n",cnf_matrix,'\n')
    print("Accuracy:",accuracy_score(y_test, y_pred))
    print("Precision:",precision_score(y_test, y_pred))
    print("Specificity:", specificity)
    print("Recall:",metrics.recall_score(y_test, y_pred))
    print("F1_score:",metrics.f1_score(y_test, y_pred))

In [14]:
# Validação Base 1

lreg_nbayes_mlp_rbf_testes(x_1,y_1,"Base 1",validacao)

---------------------------------------------------------------------
1) Regressão Logística (Base 1)
---------------------------------------------------------------------


Método validação 60/40 resutados:

Matriz de confusão:
 [[ 92 116]
 [ 56 268]] 

Accuracy: 0.6766917293233082
Precision: 0.6979166666666666
Specificity: 0.8271604938271605
Recall: 0.8271604938271605
F1_score: 0.7570621468926554

---------------------------------------------------------------------
2) Naive Bayes (Base 1)
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de confusão:
 [[156  52]
 [124 200]] 

Accuracy: 0.6691729323308271
Precision: 0.7936507936507936
Specificity: 0.6172839506172839
Recall: 0.6172839506172839
F1_score: 0.6944444444444444

---------------------------------------------------------------------
3) MPL 'adam' (Base 1)
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matr

C:\Users\Arthur\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Método validação 60/40 resutados:

Matriz de confusão:
 [[  0 208]
 [  0 324]] 

Accuracy: 0.6090225563909775
Precision: 0.6090225563909775
Specificity: 1.0
Recall: 1.0
F1_score: 0.7570093457943925

---------------------------------------------------------------------
6) RBF Gaussian Process (Base 1)
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de confusão:
 [[ 84 124]
 [ 87 237]] 

Accuracy: 0.6033834586466166
Precision: 0.6565096952908587
Specificity: 0.7314814814814815
Recall: 0.7314814814814815
F1_score: 0.6919708029197079


In [15]:
# Validação Base 2

lreg_nbayes_mlp_rbf_testes(x_2,y_2,"Base 2",validacao)

---------------------------------------------------------------------
1) Regressão Logística (Base 2)
---------------------------------------------------------------------


Método validação 60/40 resutados:

Matriz de confusão:
 [[12  8]
 [11 16]] 

Accuracy: 0.5957446808510638
Precision: 0.6666666666666666
Specificity: 0.5925925925925926
Recall: 0.5925925925925926
F1_score: 0.627450980392157

---------------------------------------------------------------------
2) Naive Bayes (Base 2)
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de confusão:
 [[15  5]
 [17 10]] 

Accuracy: 0.5319148936170213
Precision: 0.6666666666666666
Specificity: 0.37037037037037035
Recall: 0.37037037037037035
F1_score: 0.47619047619047616

---------------------------------------------------------------------
3) MPL 'adam' (Base 2)
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de 

C:\Users\Arthur\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
# Validação Base 3

lreg_nbayes_mlp_rbf_testes(x_3,y_3,"Base 3",validacao)

---------------------------------------------------------------------
1) Regressão Logística (Base 3)
---------------------------------------------------------------------


Método validação 60/40 resutados:

Matriz de confusão:
 [[12  9]
 [ 6 47]] 

Accuracy: 0.7972972972972973
Precision: 0.8392857142857143
Specificity: 0.8867924528301887
Recall: 0.8867924528301887
F1_score: 0.8623853211009174

---------------------------------------------------------------------
2) Naive Bayes (Base 3)
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de confusão:
 [[14  7]
 [ 7 46]] 

Accuracy: 0.8108108108108109
Precision: 0.8679245283018868
Specificity: 0.8679245283018868
Recall: 0.8679245283018868
F1_score: 0.8679245283018869

---------------------------------------------------------------------
3) MPL 'adam' (Base 3)
---------------------------------------------------------------------

Método validação 60/40 resutados:

Matriz de co

In [17]:
def k_fold(X, y, modelo, k=5): 
    y_pred = cross_val_predict(modelo,X,y, cv = k)
    conf_matrix = confusion_matrix(y, y_pred)
    specificity = conf_matrix[1,1]/(conf_matrix[1,0]+conf_matrix[1,1])

    print("\nMétodo k-fold (k=5) resutados:")
    print("\nMatriz de confusão:\n",conf_matrix,'\n')
    print("Accuracy:",metrics.accuracy_score(y, y_pred))
    print("Precision:",metrics.precision_score(y, y_pred))
    print("Specificity:", specificity)
    print("Recall:",metrics.recall_score(y, y_pred))
    print("F1_score:",metrics.f1_score(y, y_pred))

In [18]:
# K-fold (k=5) - Base 1

lreg_nbayes_mlp_rbf_testes(x_1,y_1,"Base 1",k_fold)

---------------------------------------------------------------------
1) Regressão Logística (Base 1)
---------------------------------------------------------------------


Método k-fold (k=5) resutados:

Matriz de confusão:
 [[261 242]
 [156 670]] 

Accuracy: 0.7005267118133935
Precision: 0.7346491228070176
Specificity: 0.8111380145278451
Recall: 0.8111380145278451
F1_score: 0.7710011507479863

---------------------------------------------------------------------
2) Naive Bayes (Base 1)
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão:
 [[384 119]
 [336 490]] 

Accuracy: 0.6576373212942062
Precision: 0.8045977011494253
Specificity: 0.5932203389830508
Recall: 0.5932203389830508
F1_score: 0.6829268292682927

---------------------------------------------------------------------
3) MPL 'adam' (Base 1)
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de con

In [19]:
# K-fold (k=5) - Base 2

lreg_nbayes_mlp_rbf_testes(x_2,y_2,"Base 2",k_fold)

---------------------------------------------------------------------
1) Regressão Logística (Base 2)
---------------------------------------------------------------------


Método k-fold (k=5) resutados:

Matriz de confusão:
 [[32 20]
 [21 43]] 

Accuracy: 0.646551724137931
Precision: 0.6825396825396826
Specificity: 0.671875
Recall: 0.671875
F1_score: 0.6771653543307087

---------------------------------------------------------------------
2) Naive Bayes (Base 2)
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão:
 [[37 15]
 [33 31]] 

Accuracy: 0.5862068965517241
Precision: 0.6739130434782609
Specificity: 0.484375
Recall: 0.484375
F1_score: 0.5636363636363637

---------------------------------------------------------------------
3) MPL 'adam' (Base 2)
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão:
 [[27 25]
 [14 50]] 

Accuracy: 0.66379310

In [20]:
# K-fold (k=5) - Base 3

lreg_nbayes_mlp_rbf_testes(x_3,y_3,"Base 3",k_fold)

---------------------------------------------------------------------
1) Regressão Logística (Base 3)
---------------------------------------------------------------------


Método k-fold (k=5) resutados:

Matriz de confusão:
 [[ 38  22]
 [ 17 106]] 

Accuracy: 0.7868852459016393
Precision: 0.828125
Specificity: 0.8617886178861789
Recall: 0.8617886178861789
F1_score: 0.8446215139442231

---------------------------------------------------------------------
2) Naive Bayes (Base 3)
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão:
 [[50 10]
 [33 90]] 

Accuracy: 0.7650273224043715
Precision: 0.9
Specificity: 0.7317073170731707
Recall: 0.7317073170731707
F1_score: 0.8071748878923767

---------------------------------------------------------------------
3) MPL 'adam' (Base 3)
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão:
 [[ 27  33]
 [ 12 111]

C:\Users\Arthur\anaconda3\lib\site-packages\sklearn\gaussian_process\_gpc.py:451: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)



Método k-fold (k=5) resutados:

Matriz de confusão:
 [[38 22]
 [24 99]] 

Accuracy: 0.7486338797814208
Precision: 0.8181818181818182
Specificity: 0.8048780487804879
Recall: 0.8048780487804879
F1_score: 0.8114754098360656

---------------------------------------------------------------------
6) RBF Gaussian Process (Base 3)
---------------------------------------------------------------------

Método k-fold (k=5) resutados:

Matriz de confusão:
 [[ 25  35]
 [ 13 110]] 

Accuracy: 0.7377049180327869
Precision: 0.7586206896551724
Specificity: 0.8943089430894309
Recall: 0.8943089430894309
F1_score: 0.8208955223880597


In [15]:
def t_test_validation(X,y, modelo, initial=1, final=11):
    t_test_validation_vector = []
    for x in range(initial,final):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=x)
        modelo.fit(X_train, y_train)
        predito = modelo.predict(X_test)
        t_test_validation_vector.append(accuracy_score(y_test, predito))
        
    return t_test_validation_vector

In [16]:
def t_test_validation_anova_tukey(x,y,base):   
    t_test_validation_reg = t_test_validation(x,y,reg)
    t_test_validation_gnb = t_test_validation(x,y,gnb)
    t_test_validation_mlp = t_test_validation(x,y,mlp)
    t_test_validation_mlp_lbfgs = t_test_validation(x,y,mlp_lbfgs)
    t_test_validation_rbf = t_test_validation(x,y,rbf)
    t_test_validation_rbf_gpc = t_test_validation(x,y,rbf_gpc)
    
    fvalue, pvalue = stats.f_oneway(t_test_validation_reg,
                                    t_test_validation_gnb, 
                                    t_test_validation_mlp,
                                    t_test_validation_mlp_lbfgs,
                                    t_test_validation_rbf,
                                    t_test_validation_rbf_gpc)
    
    print("---------------------------------------------------------------------")
    print("Teste ANOVA ("+base+")")
    print("---------------------------------------------------------------------")
    print()
    print("F-statistic:",fvalue)
    print("p-value:",pvalue)
    print()
    
    v = np.concatenate([t_test_validation_reg,t_test_validation_gnb,t_test_validation_mlp,t_test_validation_mlp_lbfgs,t_test_validation_rbf,t_test_validation_rbf_gpc])
    labels = ['reg']*len(t_test_validation_reg)+['gnb']*len(t_test_validation_gnb)+ \
     ['mlp']*len(t_test_validation_mlp)+['mlp_lbfgs']*len(t_test_validation_mlp_lbfgs)+ \
     ['rbf']*len(t_test_validation_rbf)+['rbf_gpc']*len(t_test_validation_rbf_gpc)
    
    tukey_results = pairwise_tukeyhsd(v, labels, 0.05)
    
    print("---------------------------------------------------------------------")
    print("Teste Tukey ("+base+")")
    print("---------------------------------------------------------------------")
    print(tukey_results)

In [19]:
# Teste ANOVA e Tukey - Base 1

t_test_validation_anova_tukey(x_1,y_1, "Base 1")

---------------------------------------------------------------------
Teste ANOVA (Base 1)
---------------------------------------------------------------------

F-statistic: 9.916189540560893
p-value: 9.121063205919916e-07

---------------------------------------------------------------------
Teste Tukey (Base 1)
---------------------------------------------------------------------
   Multiple Comparison of Means - Tukey HSD, FWER=0.05    
  group1    group2  meandiff p-adj   lower   upper  reject
----------------------------------------------------------
      gnb       mlp    0.031    0.9  -0.061   0.123  False
      gnb mlp_lbfgs  -0.1498  0.001 -0.2418 -0.0578   True
      gnb       rbf  -0.0318    0.9 -0.1238  0.0602  False
      gnb   rbf_gpc  -0.0342 0.8713 -0.1262  0.0578  False
      gnb       reg   0.0427 0.7185 -0.0493  0.1347  False
      mlp mlp_lbfgs  -0.1808  0.001 -0.2728 -0.0888   True
      mlp       rbf  -0.0628 0.3473 -0.1548  0.0292  False
      mlp   rbf_gpc  -0.

In [20]:
# Teste ANOVA e Tukey - Base 2

t_test_validation_anova_tukey(x_2,y_2, "Base 2")

---------------------------------------------------------------------
Teste ANOVA (Base 2)
---------------------------------------------------------------------

F-statistic: 22.452438277902456
p-value: 4.181722633206304e-12

---------------------------------------------------------------------
Teste Tukey (Base 2)
---------------------------------------------------------------------
   Multiple Comparison of Means - Tukey HSD, FWER=0.05    
  group1    group2  meandiff p-adj   lower   upper  reject
----------------------------------------------------------
      gnb       mlp    0.034 0.8213 -0.0506  0.1187  False
      gnb mlp_lbfgs  -0.1745  0.001 -0.2592 -0.0898   True
      gnb       rbf   0.0894  0.033  0.0047  0.1741   True
      gnb   rbf_gpc   0.0766 0.0978 -0.0081  0.1613  False
      gnb       reg   0.0362 0.7795 -0.0485  0.1209  False
      mlp mlp_lbfgs  -0.2085  0.001 -0.2932 -0.1238   True
      mlp       rbf   0.0553 0.3973 -0.0294    0.14  False
      mlp   rbf_gpc   0

In [21]:
# Teste ANOVA e Tukey - Base 3

t_test_validation_anova_tukey(x_3,y_3, "Base 3")

---------------------------------------------------------------------
Teste ANOVA (Base 3)
---------------------------------------------------------------------

F-statistic: 2.202796214114598
p-value: 0.06730587365445741

---------------------------------------------------------------------
Teste Tukey (Base 3)
---------------------------------------------------------------------
   Multiple Comparison of Means - Tukey HSD, FWER=0.05   
  group1    group2  meandiff p-adj   lower  upper  reject
---------------------------------------------------------
      gnb       mlp  -0.0378    0.9 -0.1604 0.0848  False
      gnb mlp_lbfgs  -0.1176 0.0674 -0.2402  0.005  False
      gnb       rbf  -0.0446 0.8848 -0.1672  0.078  False
      gnb   rbf_gpc   -0.023    0.9 -0.1456 0.0996  False
      gnb       reg      0.0    0.9 -0.1226 0.1226  False
      mlp mlp_lbfgs  -0.0797 0.4025 -0.2023 0.0429  False
      mlp       rbf  -0.0068    0.9 -0.1294 0.1159  False
      mlp   rbf_gpc   0.0149    0.9 